#!/usr/bin/env python
from __future__ import print_function
import json

import requests
from requests_oauthlib import OAuth1

try:
    from urllib.parse import urlencode
except ImportError:
    from urllib import urlencode

with open('credentials.json', 'rt') as file:
    credentials = json.load(file)

auth = OAuth1(credentials['consumer_key'],
            client_secret=credentials['consumer_secret'],
            resource_owner_key=credentials['access_token'],
            resource_owner_secret=credentials['token_secret'])


def get_collection(url, collection):
    request = requests.get(url, auth=auth)
    body = request.json()
    collection.extend(body['entries'])

    # if there is a next link, there are more pages to retrieve
    next_link = body.get('next_collection_link')
    if next_link:
        get_collection(next_link, collection)
    return collection

# get an account to search on
account_url = 'https://api.aweber.com/1.0/accounts'
accounts = get_collection(account_url, [])
account_id = accounts[0]['id']  # choose the first account

# find all subscribers across lists that match an email
params = urlencode({'email': 'example@example.com',
                    'ws.op': 'findSubscribers'})
find_url = 'https://api.aweber.com/1.0/accounts/{}?{}'.format(account_id,
                                                              params)
found_subscribers = get_collection(find_url, [])
print(json.dumps(found_subscribers, indent=4))
