#!/usr/bin/env python
from __future__ import print_function
import getpass
import json
import os

from requests_oauthlib import OAuth2Session

try:
    input = raw_input  # use raw_input in python2
except NameError:
    pass

OAUTH_URL = 'https://auth.aweber.com/oauth2/{}'

client_id = input('Enter your client id: ')
client_secret = getpass.getpass('Enter your client secret: ')

# Use your client id and secret to get an access token.
#
# See the Getting Started guide to redirect to a callback URL:
# https://api.aweber.com/#tag/Getting-Started

# Redirect URI must be https and must be one of the redirects specified
# for your integration
redirect_uri = 'https://localhost'

# Set the scopes you wish to allow
scope = [
    'account.read',
    'list.read',
    'list.write',
    'subscriber.read',
    'subscriber.write',
    'email.read',
    'email.write',
    'subscriber.read-extended'
]
oauth = OAuth2Session(
    client_id,
    redirect_uri=redirect_uri,
    scope=scope
)
authorization_url, state = oauth.authorization_url(
    OAUTH_URL.format('authorize'))

# Log in to receive a redirect url
print('Go to this URL: ' + authorization_url)
authorization_response = input('Log in and paste the returned URL here: ')

# Use the authorization response to get a token
token = oauth.fetch_token(
    OAUTH_URL.format('token'),
    authorization_response=authorization_response,
    client_secret=client_secret
)

with open('credentials.json', 'wt') as creds_file:
    json.dump({
        'client_id': client_id,
        'client_secret': client_secret,
        'token': token
    }, creds_file)
os.chmod('credentials.json', 0o600)
print('Updated credentials.json with your new credentials')
