#!/usr/bin/env php
<?php
require 'vendor/autoload.php';
use GuzzleHttp\Client;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Subscriber\Oauth\Oauth1;

// Create a Guzzle client configured to use OAuth for authentication
$stack = HandlerStack::create();
$client = new Client([
    'base_uri' => 'https://api.aweber.com/1.0/',
    'handler' => $stack,
    'auth' => 'oauth'
]);

// Load credentials into the Oauth client
$credentials = parse_ini_file('credentials.ini');
$requestMiddleware = new Oauth1([
    'consumer_key'    => $credentials['consumerKey'],
    'consumer_secret' => $credentials['consumerSecret'],
    'token' => $credentials['accessToken'],
    'token_secret' => $credentials['tokenSecret'],
]);
$stack->push($requestMiddleware);

/**
 * Get all the entries for a collection by paginating
 *
 * @param Client $client
 * @param string $url
 * @return array
 */
function getCollection($client, $url) {
    $collection = array();
    do {
        $body = $client->get($url)->getBody();
        $page = json_decode($body, true);
        $collection = array_merge($page['entries'], $collection);
        $url = isset($page['next_collection_link']) ? $page['next_collection_link'] : null;
    } while (isset($url));
    return $collection;
}


$accounts = getCollection($client, 'accounts');
$accountId = $accounts[0]['id'];
$params = array(
    'ws.op' => 'findSubscribers',
    'email' => 'example@example.com'  // email to search for
);
$find_url = 'accounts/' . $accountId . '?' . http_build_query($params);
$foundSubscribers = getCollection($client, $find_url);
print_r($foundSubscribers);
