#!/usr/bin/env php
<?php
require 'vendor/autoload.php';
use GuzzleHttp\Client;

const BASE_URL = 'https://api.aweber.com/1.0/';

// Create a Guzzle client
$client = new GuzzleHttp\Client();

// Load credentials
$credentials = parse_ini_file('credentials.ini');
$accessToken = $credentials['accessToken'];

/**
 * Get all of the entries for a collection
 *
 * @param Client $client HTTP Client used to make a GET request
 * @param string $accessToken Access token to pass in as an authorization header
 * @param string $url Full url to make the request
 * @return array Every entry in the collection
 */
function getCollection($client, $accessToken, $url) {
    $collection = array();
    while (isset($url)) {
        $request = $client->get($url,
            ['headers' => ['Authorization' => 'Bearer ' . $accessToken]]
        );
        $body = $request->getBody();
        $page = json_decode($body, true);
        $collection = array_merge($page['entries'], $collection);
        $url = isset($page['next_collection_link']) ? $page['next_collection_link'] : null;
    }
    return $collection;
}

/**
 * Print details for a webform or split test component.
 *
 * @param array $data webform or split test data
 * @param int $indent number of spaces to indent
 */
function printWebformInfo($data, $indent = 8) {
    $prefix = str_repeat(' ', $indent);
    echo "{$prefix}Type: {$data['type']}\n";
    echo "{$prefix}HTML source: {$data['html_source_link']}\n";
    echo "{$prefix}JS source: {$data['javascript_source_link']}\n";
    echo "{$prefix}Displays: {$data['total_displays']} ({$data['total_unique_displays']} unique)\n";
    echo "{$prefix}Submissions: {$data['total_submissions']}\n";
    echo "{$prefix}Conversion: " . number_format($data['conversion_percentage'], 1) . "% ";
    echo "(" . number_format($data['unique_conversion_percentage'], 1) . "% unique)\n";
}

// Get an account to manage custom fields on
$accounts = getCollection($client, $accessToken, BASE_URL . 'accounts');
$account = $accounts[0];  // choose the first account

// Get a list to get webforms for
$lists = getCollection($client, $accessToken, $account['lists_collection_link']);
$list = $lists[0];  // choose the first list


// Get all the webforms for a list
$webforms = getCollection($client, $accessToken, $list['web_forms_collection_link']);
if (empty($webforms)) {
    echo "No webforms for {$list['name']}\n";
    exit();
}

echo "Webforms for {$list['name']}:\n";
foreach ($webforms as $webform) {
    echo "    {$webform['name']}:\n";
    printWebformInfo($webform);
}

echo "\n";

// Get all the webform split tests for a list
$splitTests = getCollection($client, $accessToken, $list['web_form_split_tests_collection_link']);
if (empty($splitTests)) {
    echo "No webform split tests for {$list['name']}\n";
    exit();
}

echo "Webform split tests for {$list['name']}:\n";
foreach ($splitTests as $splitTest) {
    echo "    {$splitTest['name']}: {$splitTest['javascript_source_link']}\n";
    $components = getCollection($client, $accessToken, $splitTest['components_collection_link']);
    foreach ($components as $component) {
        echo "        {$component['name']} ({$component['weight']}%)\n";
        printWebformInfo($component, 12);
    }
}
