#!/usr/bin/env php
<?php
require 'vendor/autoload.php';
use League\Oauth2\Client\Provider\GenericProvider;


const OAUTH_URL = 'https://auth.aweber.com/oauth2/';

echo 'Enter your client id: ';
$clientId = rtrim(fgets(STDIN), PHP_EOL);
echo 'Enter your client secret: ';
$clientSecret = rtrim(fgets(STDIN), PHP_EOL);

$redirectUri = 'https://localhost';

$scopes = array(
    'account.read',
    'list.read',
    'list.write',
    'subscriber.read',
    'subscriber.write',
    'email.read',
    'email.write',
    'subscriber.read-extended'
);

// Create a OAuth2 client configured to use OAuth for authentication
$provider = new \League\OAuth2\Client\Provider\GenericProvider([
    'clientId' => $clientId,
    'clientSecret' => $clientSecret,
    'redirectUri' => $redirectUri,
    'scopes' => $scopes,
    'scopeSeparator' => ' ',
    'urlAuthorize' => OAUTH_URL . 'authorize',
    'urlAccessToken' => OAUTH_URL . 'token',
    'urlResourceOwnerDetails' => 'https://api.aweber.com/1.0/accounts'
]);

$authorizationUrl = $provider->getAuthorizationUrl();

$_SESSION['oauth2state'] = $provider->getState();

echo 'Go to this url: ' . $authorizationUrl;
echo '
Log in and paste the returned URL here: ';
$authorizationResponse = rtrim(fgets(STDIN), PHP_EOL);
$parsedUrl = parse_url($authorizationResponse, PHP_URL_QUERY);
parse_str($parsedUrl, $parsedArray);
$code = $parsedArray['code'];
echo $code;

$accessToken = $provider->getAccessToken('authorization_code', [
    'code' => $code
]);

$jsonString = json_encode($accessToken);


$fp = fopen('credentials.ini', 'wt');
fwrite($fp,
"
clientId = {$clientId}
clientSecret = {$clientSecret}
accessToken = {$accessToken->getToken()}
refreshToken = {$accessToken->getRefreshToken()}
");
fclose($fp);
chmod('credentials.ini', 0600);
echo "Updated credentials.ini with your new credentials\n";
