#!/usr/bin/env php
<?php
require 'vendor/autoload.php';
use GuzzleHttp\Client;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Subscriber\Oauth\Oauth1;

// Create a Guzzle client configured to use OAuth for authentication
$stack = HandlerStack::create();
$client = new Client([
    'base_uri' => 'https://api.aweber.com/1.0/',
    'handler' => $stack,
    'auth' => 'oauth'
]);

// Load credentials into the Oauth client
$credentials = parse_ini_file('credentials.ini');
$requestMiddleware = new Oauth1([
    'consumer_key' => $credentials['consumerKey'],
    'consumer_secret' => $credentials['consumerSecret'],
    'token' => $credentials['accessToken'],
    'token_secret' => $credentials['tokenSecret'],
]);
$stack->push($requestMiddleware);

/**
 * Get all of the entries for a collection
 *
 * @param Client $client HTTP Client used to make a GET request
 * @param string $url Relative path or full url to make the request
 * @return array Every entry in the collection
 */
function getCollection($client, $url) {
    $collection = array();
    while (isset($url)) {
        $body = $client->get($url)->getBody();
        $page = json_decode($body, true);
        $collection = array_merge($page['entries'], $collection);
        $url = isset($page['next_collection_link']) ? $page['next_collection_link'] : null;
    }
    return $collection;
}

$accounts = getCollection($client, 'accounts');
$listsUrl = $accounts[0]['lists_collection_link'];  // choose the first account
$listName = 'my list';
$params = array(
    'ws.op' => 'find',
    'name' => $listName
);
$findListUrl = $listsUrl . '?' . http_build_query($params);
$lists = getCollection($client, $findListUrl);

if (isset($lists[0]['self_link'])) {
    $tagUrl = $lists[0]['self_link'] . '/tags';  // choose the first list
    $tags = $client->get($tagUrl)->getBody();
    print_r(json_decode($tags, true));
} else {
    echo 'Could not find a list with name: ' . $listName;
}
