#!/usr/bin/env php
<?php
require 'vendor/autoload.php';
use GuzzleHttp\Client;

const BASE_URL = 'https://api.aweber.com/1.0/';

// Create a Guzzle client
$client = new GuzzleHttp\Client();

// Load credentials
$credentials = parse_ini_file('credentials.ini');
$accessToken = $credentials['accessToken'];

/**
 * Get all of the entries for a collection
 *
 * @param Client $client HTTP Client used to make a GET request
 * @param string $accessToken Access token to pass in as an authorization header
 * @param string $url Full url to make the request
 * @return array Every entry in the collection
 */
function getCollection($client, $accessToken, $url) {
    $collection = array();
    while (isset($url)) {
        $request = $client->get($url,
            ['headers' => ['Authorization' => 'Bearer ' . $accessToken]]
        );
        $body = $request->getBody();
        $page = json_decode($body, true);
        $collection = array_merge($page['entries'], $collection);
        $url = isset($page['next_collection_link']) ? $page['next_collection_link'] : null;
    }
    return $collection;
}

// Get an account to manage custom fields on
$accounts = getCollection($client, $accessToken, BASE_URL . 'accounts');
$account = $accounts[0];  // choose the first account

// Get a list to manage custom fields on
$listsUrl = $account['lists_collection_link'];
$lists = getCollection($client, $accessToken, $listsUrl);
$list = $lists[0];  // choose the first list

// Check if custom fields already exist with the names we use below
$customFieldsUrl = $list['custom_fields_collection_link'];
$customFields = getCollection($client, $accessToken, $customFieldsUrl);
foreach ($customFields as $entry) {
    if (in_array($entry['name'], ['Test', 'Renamed'], true)) {
        echo "A custom field called {$entry['name']} already exists on {$list['name']}\n";
        exit();
    }
}

// Create a custom field called Test
$createResponse = $client->post($customFieldsUrl, [
    'form_params' => ['ws.op' => 'create', 'name' => 'Test'],
    'headers' => ['Authorization' => 'Bearer ' . $accessToken]]);
$fieldUrl = $createResponse->getHeader('Location')[0];
echo "Create new custom field at {$fieldUrl}\n";

// Update the custom field
$updateResponse = $client->patch($fieldUrl, [
    'json' => ['name' => 'Renamed', 'is_subscriber_updateable' => true],
    'headers' => ['Authorization' => 'Bearer ' . $accessToken]]);
$updatedField = json_decode($updateResponse->getBody(), true);
echo "Updated the custom field: ";
print_r($updatedField);

// Delete the custom field
$client->delete($fieldUrl, 
    ['headers' => ['Authorization' => 'Bearer ' . $accessToken]]);
echo "Deleted the custom field\n";
